### ISSUE TITLE
Accidentally disabled Fader in Dalamud Plugins, now doesn't appear in list

### ISSUE THREAD

**Issue by NianteNadie** [shdwp/xivFaderPlugin#12]
I misclicked on "disable" in the Dalamud plugin installer window. Now it is gone from both my installed and available plugins. I tried using the "clear hidden plugins" function in Dalamud settings to no avail. Is there a way to fix this?

**Comment by Kasper-Who** [comment]
It's currently disabled for everyone as it was causing crashes. I'd assume it'll reappear once they've fixed it.

**Comment by shdwp** [comment]
Fixed.

**Comment by NianteNadie** [comment]
Excellent. Thank you so much for your work.
