### ISSUE TITLE
TargetInfo doesn't show when targeting self (HasPlayerTarget)

### ISSUE THREAD

**Issue by oorzkws** [shdwp/xivFaderPlugin#13]
Hitting F1 to target myself should, theoretically, show the TargetInfo bar but it does not. 

Matrix:
![image](https://user-images.githubusercontent.com/65210810/146755787-c197b1a3-7fb4-4f13-97ce-14cd4cebe3cb.png)

**Comment by oorzkws** [comment]
Addendum: It also doesn't show in other cases. If I'm idle and then target a dummy, it will show. However, if I then tab to the second dummy beside it, TargetInfo no longer shows.

**Comment by shdwp** [comment]
There is a recent bug with the latest update that screws up target infos. Will fix.
