### ISSUE TITLE
Cannot right-click TargetInfo

### ISSUE THREAD

**Issue by oorzkws** [shdwp/xivFaderPlugin#15]
This is new as of today. I normally right click the TargetInfo bar to reset striking dummy enmity, I now cannot.

Matrix:
![image](https://user-images.githubusercontent.com/65210810/146756102-23c8ed71-ecde-417c-a64e-5c3c9540f48a.png)

**Comment by shdwp** [comment]
Reproduced, will fix later.

**Comment by shdwp** [comment]
Should be fixed in next update.
