### ISSUE TITLE
Parameter option completly hides DelvUI

### ISSUE THREAD

**Issue by Dajova** [shdwp/xivFaderPlugin#16]
I noticed that the new update today have a weird interaction with DelvUI. Making Parameter bars hide, completely hides DelvUI as well.

[issue](https://i.imgur.com/rFIjRVS.mp4)

I'm guessing this isnt the intended behaviour...

edit: I also noticed that the User Focus key doesnt work either, with neither option enabled.

**Comment by shdwp** [comment]
I don't know how delv ui operates, but if it just anchors to the parameter bars visibility to hide its own elements there's not much to be done there.

It only appeared today because update changed the way plugin actually hides things (crash prone).

**Comment by shdwp** [comment]
I will revert to old method of hiding in the next release, this will return this behavior as it was before.

**Comment by shdwp** [comment]
Should be fixed in next update.
