### ISSUE TITLE
Click through the hotbars after changing map

### ISSUE THREAD

**Issue by iamjilao** [shdwp/xivFaderPlugin#18]
After the first time changing the map, despite "show" or "hide", my hotbars are all click-through, no tooltip showing up, cannot drag skills in or out, yet the bars and icons are still there, and the keybinds work normally. Can only be clickable after restarting the game.
Love ur plugin, I really appreciate that I don't have to manually hide my hotbars whenever not in an instance.

**Comment by shdwp** [comment]
Should be fixed in next update.
