### ISSUE TITLE
Minimap hiding incompatible with Compass plugin

### ISSUE THREAD

**Issue by Telostai** [shdwp/xivFaderPlugin#21]
I'm not sure if this is possible, but just throwing it out there to see.
Currently, using Compass plugin, if I hide my minimap via normal in-game means, Compass continues to function. If I hide with Fader, Compass disappears altogether, as if the minimap is entirely unloaded instead of just hidden.
Any thoughts on changing the "hiding method" used on the minimap to function more like toggling the visibility in HUD settings? If it's possible, that'd be phenomenal.

**Comment by Telostai** [comment]
After the update, this is no longer an issue. But now the parameters bar refuses to hide and brings back the old issue where Fader doesn't play nice with the Combo Timer from Simple Tweaks (unless using the alternative UI attachment method for Combo Timer).

**Comment by shdwp** [comment]
I'm going to close this since the original issue has been resolved.
