### ISSUE TITLE
Hide UI items while mounted option request

### ISSUE THREAD

**Issue by crashburn82** [shdwp/xivFaderPlugin#22]
Firstly, Thank you for this addon. Would be great if we  can  hide hotbars and other UI items while mounted as the only in game  option is to hide the  whole UI.

**Comment by shdwp** [comment]
Good suggestion.

**Comment by Aelexe** [comment]
Thank you for this suggestion. This feature will be included in the upcoming v2.0.0.0 release.

**Comment by crashburn82** [comment]
Thank you very much for adding this in. Its also good to see the addon will be updated, missed it alot. Cheers
