### ISSUE TITLE
Feature Req: Activity based chat

### ISSUE THREAD

**Issue by WesBosch** [shdwp/xivFaderPlugin#26]
I know this is asking a lot, but is it possible to have chat show when active/message recieved, then hide again on timeout with the idle timer? I'm not sure if it's possible to watch the chat for activity, but it may be possible to utilize ChatAlert plugin's filters maybe?

This is the *only* plugin that hides the chat tho and I am forever thankful with what it is already!

**Comment by gucciBane** [comment]
This would be fantastic. I dunno if it's possible, but one of the few things I wish FFXIV had in vanilla.

**Comment by Aelexe** [comment]
Thank you for submitting this feature request. I've implemented it and it will be included in the next release.
