### ISSUE TITLE
Issue: Hidden items are still clickable

### ISSUE THREAD

**Issue by gucciBane** [shdwp/xivFaderPlugin#27]
I run into this issue sometimes. If your hotbars are unlocked, it compounds the issue because you can mistakenly click invisible things while trying to camera turn and toss them off into space.

https://user-images.githubusercontent.com/49180180/147867460-b82e4709-2e46-4d71-ae83-3d3fa9be9161.mp4

**Comment by shdwp** [comment]
Known issues, don't think this will be fixed anytime soon.
