### ISSUE TITLE
Hotbar Alpha levels not preserved 

### ISSUE THREAD

**Issue by Zinterax** [shdwp/xivFaderPlugin#29]
Currently if you set hot bars to have a lower alpha so they're less visible the plugin appears to be setting it back to 100% visibility when it matches a "show" condition.

**Comment by shdwp** [comment]
Can you set your hotbar alpha in game?

**Comment by Zinterax** [comment]
Yes; hotbar alpha is a built in feature of the base game. It doesn't stand out too much in the options but it's this slider when you inspect the options of a UI element.

![image](https://user-images.githubusercontent.com/2131699/148415740-f91ff5d1-4d6d-46cd-9fa0-96e4d0a01a6b.png)

**Comment by shdwp** [comment]
Okay, I'll see how can I fix this one later.

**Comment by iamjilao** [comment]
> Okay, I'll see how can I fix this one later.

Is there a way to download a rollback version? The last 5 days was a dilemma struggle for me, I have to either activate Fader with eye-blinding 0 transparency hotbars and parameter or live without the serenity that Fader gave me. However, ty for ur work and the amazing partyicons plugin.

**Comment by Aelexe** [comment]
Thank you for submitting this issue. This should be fixed as part of the re-implementation of our fading logic, either in the current or upcoming v2.0.0.0 release.
