### ISSUE TITLE
"TargetNPC" not working with town NPCs

### ISSUE THREAD

**Issue by andreycout** [shdwp/xivFaderPlugin#30]
Apparently the target NPC condition isn't working. In towns it doesn't apply my rules when I target NPCs. Maybe it only counts for friendly NPCs in instances and such (ones that have lifebars etc)? Haven't tested it yet. I was hoping I could hide most of the HUD when targeting NPCs in towns so I could focus on dialogue without all the clutter...

**Comment by Aelexe** [comment]
Thank you for raising this issue. I've implemented target manager to more accurate assess NPC types but there are a few edge cases where what appears to be an NPC target is a combat target instead.

For most uses cases this should now be fixed.
