### ISSUE TITLE
Request: More macro commands

### ISSUE THREAD

**Issue by athuy** [shdwp/xivFaderPlugin#32]
A command to strictly enable/disable the plugin, rather than just toggle it would be appreciated for macro usage. 
Other commands to show/hide specific UI elements would also be nice.

**Comment by Infiziert90** [comment]
#65

Added 2 new commands, "on" and "off". 

I also don't think it would be a good idea to allow commands to hide and show specific elements of the UI, as this could easily lead to weird behaviours.
