### ISSUE TITLE
Update for patch 6.1?

### ISSUE THREAD

**Issue by Krojack** [shdwp/xivFaderPlugin#33]
Just curious if this project is dead or it an update will come for patch 6.1.

Edit: Crap I forgot the dev is from Ukraine. Take your time man. Wish you well.

**Comment by shdwp** [comment]
I'm just hoping that someone else will come and maintain this. I've found maintainers for other plugins but fader is still an orphan unfortunately.

**Comment by XenHat** [comment]
> I'm just hoping that someone else will come and maintain this. I've found maintainers for other plugins but fader is still an orphan unfortunately.

I'm fairly new to the plugins community but I have several years of experience in C++ and C#.
I would be interested in keeping the plugin running at the very least (as a maintainer, until I learn enough API to help with the features/refactoring).

**Comment by Langboule** [comment]
Just showing my support for this cool plugin. I hope it will be updated!

**Comment by RyudoGaming** [comment]
I've been maintaining Side Hud, as it was abandoned months ago, I have added some new options and it still runs but no 0 C# so the fact it's actually still running is great, hopefully someone can do the same here.

**Comment by ProfessorBAG** [comment]
Hello! Just wanted to say i love and miss this plugin! Here's hoping we can get an update whenever you decide to work on it again. In the meantime thank you for letting me enjoy it in the past!

**Comment by shdwp** [comment]
I'm sorry. I'm gutted to read comments like that, but I just don't have any time now. With the war and me moving out of the country I'm stuck in the seemingly never-ending process of changing apartments, looking for a new job, working at an current job, going to the immigration offices, registering my car, getting new drivers license. 

I had hoped that someone would pick up and maintain Fader,  but unfortunately that didn't happen. I will update it one day, when I get back to playing XIV, but I can't even say when that is going to happen.
