### ISSUE TITLE
[Plugin Conflict] Simple Tweaks - Combo Timer

### ISSUE THREAD

**Issue by SubaruYashiro** [shdwp/xivFaderPlugin#41]
If you use hide parameter with Simple Tweaks - Combo Timer, parameter bar won't be hidden, and the Combo Timer instead would be re-apply multiple times and it become bolder as time goes on, and it also blink once in a while. I'm not sure if this issue can be fixed in Fader side or it should be on SimpleTweaks's side 
Before Fader + Combo Timer:
![image](https://user-images.githubusercontent.com/96951106/179433121-7d73be87-5300-4549-9f48-94944b111f19.png)
After Fader + Combo Timer:
![image](https://user-images.githubusercontent.com/96951106/179433200-93277e5c-ac21-4ea4-a8a4-663ced53fa95.png)

**Comment by Aelexe** [comment]
Thank you for submitting this issue. This should be fixed as part of the re-implementation of our fading logic, either in the current or upcoming v2.0.0.0 release.
