### ISSUE TITLE
User Focus Key not working

### ISSUE THREAD

**Issue by dekahn** [shdwp/xivFaderPlugin#47]
Per title pressing the User Focus Modifier Key does not make the UI reappear.

**Comment by dekahn** [comment]
also "always user focus when hotbars are unlocked" not working as well.

**Comment by Kasper-Who** [comment]
You need to add "User Focus" as a condition now under each section.

**Comment by dekahn** [comment]
Ah ok, thanks.

**Comment by Krojack** [comment]
Yeah this confused me too. Maybe rename the "User Focus" to something like "Hotkey Focus"?
