### ISSUE TITLE
6.2 update

### ISSUE THREAD

**Issue by serwiibox** [shdwp/xivFaderPlugin#49]
Hi, I love your plugin, It makes the game more enjoyable. I was wondering when the new update is coming out.
Thanks ofr your amazing job!

**Comment by Aelexe** [comment]
Thank you for your kind words. I pushed the new released to the plugin repo yesterday so it will be available as soon as the pull request is merged.

**Comment by shdwp** [comment]
Yeah, you've been doing quite a work on this Aexele!
