### ISSUE TITLE
Island sanctuary

### ISSUE THREAD

**Issue by serwiibox** [shdwp/xivFaderPlugin#51]
I was wondering if is posible to add and option for Island sactuary to hide and show things. Thanks for your work!

**Comment by Aelexe** [comment]
Thank you for the suggestion, I can look into that for you. Were you hoping to hide Island Sanctuary UI elements (and if so which ones), or have the Island Sanctuary as a condition for hiding elements?

**Comment by RitzyBusiness** [comment]
Island Sanctuary is seen as a duty so you cant hide your UI there unless you want your dungeons to have hidden UI's.

**Comment by siklr** [comment]
@Aelexe 
I did some preliminary research into creating a state for this and found that if we check to see if the territory's intended use is type 49 it should cover current Island Sanctuary areas and any future ones they might release. I could work on implementing this if that's ok.

@serwiibox @RitzyBusiness 
Is there a want or need to hide Island Sanctuary specific UIs? Or is it that the request is asking for a new state and nothing else?

**Comment by RitzyBusiness** [comment]
> @Aelexe I did some preliminary research into creating a state for this and found that if we check to see if the territory's intended use is type 49 it should cover current Island Sanctuary areas and any future ones they might release. I could work on implementing this if that's ok.
> 
> @serwiibox @RitzyBusiness Is there a want or need to hide Island Sanctuary specific UIs? Or is it that the request is asking for a new state and nothing else?

For me I am requesting a new state so Island Sanctuary acts like my UI does out of combat or in duty.

**Comment by Aelexe** [comment]
@siklr
> I could work on implementing this if that's ok.

Feel free to. I'll look it over for you once it's done.

**Comment by Infiziert90** [comment]
#61 

With this update the Duty state also doesn't apply anymore if the user is on the island
