### ISSUE TITLE
Request: Another User Focus Toggler

### ISSUE THREAD

**Issue by Rellawing** [shdwp/xivFaderPlugin#52]
A second focus key would be badass. My proposal would allow for a lovely setup that we can't achieve with just one user focus toggler unless someone knows of a workaround.

You can overlap multiple hotbars in one space and as you hold the focus key, That hotbar replaces one that disappears. In essence, it makes for the ultimate clean UI that I've always dreamed of in FFXIV.

I sure hope you can make it happen!

Addition: If another focus key is added, of course we'd need to be able to assign that focus to a particular hotbar (or multiple hotbars). Just adding this functionality would double the utility of the mod.

**Comment by Infiziert90** [comment]
Next update will add 3 new conditions, ALT, SHIFT and CTRL.
With this you can make your idea come true, without any need of changing your focus toggle at all.

**Comment by Infiziert90** [comment]
Update 2.5.0.0 closes this comment

**Comment by Rellawing** [comment]
This is wonderful news! Thank you!
