### ISSUE TITLE
6.3 update

### ISSUE THREAD

**Issue by serwiibox** [shdwp/xivFaderPlugin#55]
Hi!, i was wondering if is posible to update the plugin for the 6.3 update. Thanks in advance!

**Comment by I-Koloki-I** [comment]
I second this request, there is nothing else with quite the same functionality

**Comment by RitzyBusiness** [comment]
It says decommissioned in dalamud, so its unlikely to get updated unless thats an error.  Just gonna hafta find something else, wait, or maybe its just not possible anymore or too complicated to implement with the UI changes.

**Comment by Aelexe** [comment]
It may have been decommissioned because I haven't updated it in a while as I've stopped playing FF14 regularly.

I will hopefully be able to look into this over the weekend.

**Comment by Dasky14** [comment]
This plugin is the one thing that keeps my UI clean outside of combat, so it'd be a shame for it to not update.
I hope you have the time to look into it.

**Comment by Rellawing** [comment]
I very much miss my clean UI courtesy of Fader. I hope the author is safe and alright! Please rejoin us when you can!

**Comment by Krojack** [comment]
I see a message on the discord that this was updated to Version 2.3.1.0 but mine isn't updating.. Did something change? Should I delete and reinstall it?

**Comment by FromTheGrayve** [comment]
I saw that message to, and deleted my old install. But now Fader isn't even listed as a plugin to dl.

**Comment by Krojack** [comment]
I asked on Discord and they said it was a known problem and that it will be fixed. I'll just wait it out.

**Comment by Rycia** [comment]
Still needing this back.

**Comment by Infiziert90** [comment]
Fixed in the newest release :3 
Please update using dalamud

**Comment by FromTheGrayve** [comment]
Thanks!
