### ISSUE TITLE
Fader not appearing in the plugin installer

### ISSUE THREAD

**Issue by RatboyFlip** [shdwp/xivFaderPlugin#58]
Hello! After the 6.3 Fader Plugin update, it is not appearing in the XIVLauncher plugin installer. I have seen on the XIVLauncher/Dalamud Discord that the Dev has been made aware, but I am curious if you have a timeframe on when you may be able to update/fix this bug. Thank you for your hard work!! 👍
![3e84c8d4b785bc452dae2b49a1abbbbf](https://user-images.githubusercontent.com/123054711/214979575-39a6b47f-957a-476f-b3cb-3d8f64da10a1.png)

**Comment by Senabun** [comment]
Any updates on when Fader will come back? I miss it. ;-;

**Comment by Rellawing** [comment]
They abandon us. ; _ ;

**Comment by Krojack** [comment]
While I have no clue what's going on, remember that the dev for this plugin is from Ukraine. They might not be in a position to do updates that often.

**Comment by Infiziert90** [comment]
Fixed in the newest release :3 
Please update using dalamud
