### ISSUE TITLE
[Feature Request] Condition Weapon Drawn

### ISSUE THREAD

**Issue by Rellawing** [shdwp/xivFaderPlugin#59]
Thanks for bringing Fader back! I missed it majorly! I was able to retire my wonky standard ui toggling system offline with the reappearance of Fader! <3

I have a request though... would you mind adding Weapon Drawn as a condition? (If I draw my weapon, I want main hotbars to show)

Edited: That bug was just me. XD  I love to check the option to permanently toggle user focus but it had been a while and forgot how that works. Btw, Weapon Drawn would still be a far more handy way to see our hidden bars (just press Z and good to go) instead of (hold shift, click padlock,then edit), which makes it a single step instead of two. (not to mention way cooler!)

**Comment by Infiziert90** [comment]
Added in #60
