### ISSUE TITLE
The Fader doesn't seem to be able to hide Parameters anymore

### ISSUE THREAD

**Issue by Shoedonym** [shdwp/xivFaderPlugin#6]
They disappear for less than a second and and come back immediately for me.

**Comment by Iaotle** [comment]
This is an issue with gatherers I believe.

**Comment by Shoedonym** [comment]
> This is an issue with gatherers I believe.

Nope. I fixed it. The issue is the Simple Tweaks plugin's Combo Timer feature. You need to enable the "Alternative UI Attachment" setting on that or the Parameters can't fade.
