### ISSUE TITLE
Suggestion: Add a separate category for Bozja

### ISSUE THREAD

**Issue by Iaotle** [shdwp/xivFaderPlugin#8]

**Comment by shdwp** [comment]
I think there are more than enough categories as it is. Too many in my opinion.

**Comment by Iaotle** [comment]
But the purpose of the plugin is to provide convenient HUD hiding,  is it not? I want to use it in Bozja, and hide things specific to Bozja. If people don't want to use it for bozja they can just skip the setup of that category, no?

**Comment by shdwp** [comment]
I'll add Bozja after I redesign the UI.

**Comment by Iaotle** [comment]
:)
