### ISSUE TITLE
[Feature Request] Option to show UI element on mouseover/hover

### ISSUE THREAD

**Issue by ryankhart** [shdwp/xivFaderPlugin#85]
My use case that I want for this plugin is to put some vertical hotbars on the sides of my screen with no key binds assigned to them, but I want them to be hidden until I hover my mouse pointer over them which makes them show again.

**Comment by Infiziert90** [comment]
Won't be implemented like this in Fader

An easier solution would be collapseable hotbars
Just make a macro that unhides the hotbars for x seconds and fills it with content from some job like arcanist
There is alot of guides online how these hotbars work :)

**Comment by ryankhart** [comment]
That's fair. I don't know how difficult it would have been to implement this kind of mouse hover detection over native UI elements, anyway. Probably a nightmare to implement, but I thought I'd ask just in case.

I guess, I'll just hope that one day SE implements this feature natively since, I don't want to bother with clicking another button first to unhide a hotbar, if I wanted that, I'd just use the Main Menu instead since most of what I put on my side hotbars are just shortcuts to items in the Main Menu because I want to click once, not twice.
