### ISSUE TITLE
Bug: Duty section overwrittes everything

### ISSUE THREAD

**Issue by Dajova** [shdwp/xivFaderPlugin#9]
So it seems like the duty section overwrites everything else that you have set, even if its set to skip. It still doesnt hide/show on anything you've set otherwise as long as you are in a instance..

**Comment by shdwp** [comment]
Reproduced, will fix in next update.

**Comment by Dajova** [comment]
Dunno if its related, but the last update also made it so the bars hidden in duties becomes unclickable when you exit the duty.

[issue](https://i.imgur.com/NHMLuSf.gif)

**Comment by shdwp** [comment]
Should be fixed in next update.
